# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy build to TestFlight"
  lane :deploy_to_testflight do
    # add actions here: https://docs.fastlane.tools/actions

    # 0. Prepare the CI environment (creates the keychain, etc)
    setup_ci if is_ci

    # 1. Auth with App Store Connect API Key
    key_id = ENV["APP_STORE_CONNECT_KEY_ID"]
    issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    key_content = ENV["APP_STORE_CONNECT_KEY_CONTENT"]

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content.gsub('\n', "\n"),
      is_key_content_base64: false
    )

    # 2. Match to sync provisioning profiles and certificates
    
    match(
      type: "appstore", 
      api_key: api_key,
      readonly: true
    )

    # 3. Increment build number
    increment_build_number(xcodeproj: "App.xcodeproj")

    # 4. Build the app
    gym(
      scheme: "App",
      workspace: "App.xcworkspace",
      output_directory: "./build",
      output_name: "App.ipa",
      export_method: "app-store"
    )

    # 5. Upload to TestFlight
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Generate or update provisioning profiles and certificates"
  lane :sync_certificates do
    # 1. Auth with App Store Connect API Key
    key_id = ENV["APP_STORE_CONNECT_KEY_ID"]
    issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    key_content = ENV["APP_STORE_CONNECT_KEY_CONTENT"]

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content.gsub('\n', "\n"),
      is_key_content_base64: false
    )

    # 2. Register the App ID in the Apple Developer Portal
    # this creates the App ID if it doesn't exist, but if it already exists it will just return it, so it's safe to run multiple times
    # this step have issues with an account with 2FA enabled
=begin
    produce(
      app_identifier: "com.luismdev.capacitor-build-ga.v1",
      app_name: "Capacitor Github Action",
      language: "English",
      sku: "com.luismdev.capacitor-build-ga.v1",
      skip_itc: true, # Skip creating the app in App Store Connect, we just want to create the App ID in the Developer Portal
    )
=end

    # 3. Match to sync provisioning profiles and certificates
    match(
      type: "appstore", 
      api_key: api_key,
      readonly: false
    )
  end
end
